name: Build .NET Framework Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Step 1: Check out the code from your repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup MSBuild
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      # Step 3: Setup NuGet
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1

      # Step 4: Restore NuGet packages
      - name: Restore NuGet packages
        run: nuget restore ClashRoyale.sin

      # Step 5: Build the solution using MSBuild
      - name: Build solution
        run: msbuild ClashRoyale.sin /p:Configuration=Release
